In [1]:
import numpy as np

# 031

ndarray 곱셈

전체 데이터에 10을 곱한 결과를 ndarray에 저장하세요.

data = [1, 2, 3]

In [2]:

data = [1, 2, 3]

arr = np.array(data)*10

# 032

ndarray 제곱

전체 데이터에 제곱한 결과를 ndarray에 저장하세요.

data = [1, 2, 3]

In [3]:

data = [1, 2, 3]

arr = np.array(data)**2

# 033

ndarray 루트

전체 데이터에 루트를 적용한 결과를 ndarray에 저장하세요.

data = [1, 2, 3]

In [4]:
data = [1, 2, 3]

arr = np.array(data)**1/2

# 034

ndarray 컬럼 평균

다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.

score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

과목별 평균 점수를 출력하세요.

[12. 18.]

In [11]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

score.mean(axis=0) #열 기준 평균 계산

array([12., 18.])

# 035

ndarray 로우 표준편차

다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.

score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
중간고사와 기말고사의 표준편차를 출력하세요.

[5. 1.]


In [13]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

score.std(axis=1) #행 기준 표준편차 계산

array([5., 1.])

# 036

행렬곱

두 행렬의 곱셉결과를 출력하세요.

> a = np.arange(   4).reshape(2,2)

> a
[[0 1]
 [2 3]]

> b = np.arange(1, 5).reshape(2,2)

> b
[[1 2]
 [3 4]]

In [14]:

a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)

np.matmul(a,b)


array([[ 3,  4],
       [11, 16]])

# 037

전치행렬

다음의 ndarray로 행과 열의 위치를 바꾼 전치행렬을 출력하세요.

arr = np.arange(9).reshape(3, 3)

In [18]:
arr = np.arange(9).reshape(3, 3)

arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

# 038

짝수 배열

다음 배열에서 짝수 값만 추출하세요.

import numpy as np

arr = np.arange(10)

In [19]:
arr = np.arange(10)

arr[2::2]

array([2, 4, 6, 8])

# 039

홀수 배열

다음 배열에서 홀수 값만 추출하세요.

import numpy as np

arr = np.arange(10)

In [20]:
arr = np.arange(10)

arr[1::2]

array([1, 3, 5, 7, 9])

# 040

여러 조건

다음 배열에서 3보다 크고 7보다 작은수만 추출하세요

import numpy as np

arr = np.arange(10)

In [22]:
arr = np.arange(10)

arr[3:7]

array([3, 4, 5, 6])