In [2]:
import numpy as np

# 041

조건에 맞는 원소값 출력

다음 ndarray 객체에서 음수를 출력하세요.

arr = np.array([-1, 2, -3, 4])

In [3]:
arr = np.array([-1, 2, -3, 4])

arr[arr<0]

array([-1, -3])

# 042

조건에 맞는 원소값 변경

다음 ndarray 객체에서 음수를 0으로 치환하세요

arr = np.array([-1, 2, -3, 4])

In [11]:
arr = np.array([-1, 2, -3, 4])

arr[arr<0] = 0

# 043

조건에 맞는 원소값 변경

다음 ndarray 객체에서 음수를 양수로 변환하세요

arr = np.array([-1, 2, -3, 4])

In [12]:
arr = np.array([-1, 2, -3, 4])

a = arr<0 

arr[a] = -arr[a]

# 044

조건에 맞는 원소값 변경

다음 ndarray 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요.

arr = np.array([-1, 2, -3, 4])

In [13]:
arr = np.array([-1, 2, -3, 4])

a = arr>0
b = arr<0

arr[a] = arr[a]+10
arr[b] = arr[b]-10

# 045

shuffle

numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 섞어 보세요.

arr = [1, 2, 3, 4, 5]


In [15]:
arr = [1, 2, 3, 4, 5]

np.random.shuffle(arr)

# 046

argmin

다음 넘파일 배열에서 최솟값의 인덱스를 출력하세요.

arr = np.array([1, 2, 3, 4, 5])

arr = np.array([1, 2, 3, 4, 5])

np.argmin(arr)

# 047

argmin

다음 넘파일 배열에서 최댓값의 인덱스를 출력하세요.

arr = np.array([1, 2, 3, 4, 5])

In [16]:

arr = np.array([1, 2, 3, 4, 5])

np.argmax(arr)

4

# 048

정렬

다음 넘파이 배열을 오름차순 정렬해보세요.


arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# 049

numpy.vstack

numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요.

array([[1, 2],
       [3, 4]])
       
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

In [20]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4]])

# 050

flatten

flatten 메서드를 사용하여 다음 배열을 1차원 배열로 변경하세요.

arr = np.array([ [1, 2], [3, 4] ])

In [22]:
arr = np.array([ [1, 2], [3, 4] ])

arr.flatten()

array([1, 2, 3, 4])