In [2]:
import numpy as np

# 021

astype

arr 배열은 float64 타입입니다. 이를 np.int32 타입으로 변경하세요.

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

In [3]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

arr1 = arr.astype(np.int32)

# 022

linspace

0~10 사이를 구간을 20개의 포인트로 분할한 결과를 ndarray로 표현하라.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [4]:

np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# 023

로우 인덱싱

다음의 ndarry 객체에서 마지막 로우([6, 7, 8])을 출력하세요.

> arr = np.arange(9).reshape(3, 3)

> arr
[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [13]:
arr = np.arange(9).reshape(3, 3)
arr[2,:]

array([6, 7, 8])

# 024

컬럼 인덱싱

다음의 ndarry 객체에서 두 번째 컬럼([1, 4, 7])을 출력하세요.

> arr = np.arange(9).reshape(3, 3)

> arr
[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [6]:
arr = np.arange(9).reshape(3, 3)

arr[:,1]

array([1, 4, 7])

# 025

데이터 인덱싱

다음의 ndarray 객체에서 17을 선택하는 코드를 작성하라.

> arr = np.arange(25).reshape(5, 5)

> arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [7]:
arr = np.arange(25).reshape(5, 5)

arr[3,2]

17

# 026

슬라이싱

[1 3]을 슬라이싱 하는 코드를 작성하세요.

> arr = np.arange(5)

> arr
[ 0  1  2  3  4]

In [8]:
arr = np.arange(5)

arr[1:4:2]

array([1, 3])

# 027

슬라이싱

[6 7 8 9]를 슬라이싱 하는 코드를 작성하세요.

> arr = np.arange(25).reshape(5, 5)

> arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [9]:
arr = np.arange(25).reshape(5, 5)

arr[1,1:]

array([6, 7, 8, 9])

# 028

슬라이싱

첫번째와 두번째 컬럼을 슬라이싱하는 코드를 작성하세요.

> arr = np.arange(25).reshape(5, 5)

> arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [10]:
arr = np.arange(25).reshape(5, 5)

arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

# 029

슬라이싱

6. 7,11, 12 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.

> arr = np.arange(25).reshape(5, 5)

> arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

In [11]:
arr = np.arange(25).reshape(5, 5)

arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

# 030

슬라이싱

0. 3,20, 23 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.

> arr = np.arange(25).reshape(5, 5)

> arr
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [12]:
arr = np.arange(25).reshape(5, 5)
arr[ [0, -1] , [0, 3] ]

array([ 0, 23])