In [6]:
import numpy as np

# 011

차원 배열

다음과 같이 2차원 ndarray 객체를 정의하세요.

[[0 1 2]
 [3 4 5]]

In [7]:
arr = np.arange(6).reshape(2,3)

# 012

ones

1이 20개 저장된 아래의 ndarray 객체를 만들어 보세요.

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [9]:
data = [1] * 20

arr = np.array(data)

# 013

ones

4행 5열로 저장된 아래의 ndarray 객체를 만들어 보세요.

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

In [10]:
data = [1]*20

arr = np.array(data).reshape(4,5)

# 014

ones

255로 채워진 10X10 크기의 ndarray 객체를 생성하세요.

In [11]:
data = [255]*100

arr = np.array(data).reshape(10,10)

# 015

zeros

3x4 (행x열) 크기의 0으로 채워진 배열을 생생해보세요.

In [12]:
data = [0]*12

arr = np.array(data).reshape(3,4)

# 016

dtype

[1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.

In [13]:
data = [1, 2, 3]

arr = np.array(data, dtype = np.int32)

# 017

다음 배열의 데이터 타입을 확인해보세요.

arr = np.array([1, 2, 3])

In [15]:
arr = np.array([1, 2, 3])

arr.dtype

dtype('int64')

# 018

dtype

다음 배열의 데이터 타입을 확인해보세요.

arr = np.array(['1', '2', '3'])

In [16]:
arr = np.array(['1', '2', '3'])

arr.dtype

dtype('<U1')

# 019

dtype

다음 데이터를 np.int16 타입의 배열로 형변환하세요.

arr = np.array([1, 2, 3])

In [17]:
arr = np.array([1, 2, 3], dtype = np.int16)

# 020

데이터 타입

300이 44로 출력되는 이유를 설명하세요.

> a = np.array( [ 255, 300, 128], dtype=np.uint8 )
> a
[255  44 128]


정답 : 8비트는 300까지 표현할 수 없기에 잘못된 값이 표출됨