# 001

넘파이 임포트

넘파이 모듈을 np라는 이름으로 임포트해보세요.

In [1]:
import numpy as np

# 002

ndarray

리스트를 넘파이의 ndarray 객체로 변환해보세요.

data = [1, 2, 3]

In [2]:
data = [1, 2, 3]

arr = np.array(data)

# 003

arange

0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요

In [3]:
arr = np.arange(100)

# 004

arange

구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요.

> arr
[ 3  6  9 12 15 18 21 24 27]

In [4]:

arr = np.arange(1,10)*3

# 005

arange

1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.



In [5]:
arr = np.arange(2,1000,2)

# 006

실수 range

0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.

In [6]:
arr = np.arange(0,1,0.1)

# 007

reshape

리스트에는 6개의 데이터가 저장돼 있습니다.

data = [0, 1, 2, 3, 4, 5]

다음과 같이 2행 3열의 ndarray로 변환하세요.

[[0 1 2]
 [3 4 5]]


In [9]:
data = [0, 1, 2, 3, 4, 5]

arr = np.array(data).reshape(2,3)

# 008

reshape

다음의 2차원 ndarray 1차원 ndarray로 변환하세요.

arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

In [10]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

arr.reshape(6)

array([0, 1, 2, 3, 4, 5])

# 009

reshape

주어진 ndarray를 다음과 같이 변경해 보세요.

arr = np.arange(3)

[[0]
 [1]
 [2]]

In [11]:
arr = np.arange(3)

arr.reshape(3,1)

array([[0],
       [1],
       [2]])

# 010

에러의 원인

에러의 원인을 설명하세요.

> np.arange(6).reshape(2, 4)
ValueError: cannot reshape array of size 6 into shape (2,4)


정답 : 데이터는 6개인데 8개를 호출하려함